train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "/home/wbhz_hw_guzheng/mindformers/wikitext-2049/wikitext-2049/wikitext-2049.mindrecord"
    shuffle: False
#    num_samples: 4096
  input_columns: ["input_ids"]  # "input_mask", "label_ids"
  num_parallel_workers: 10
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 8
  repeat: 10
  numa_enable: False
  prefetch_size: 10

train_dataset_task:
  type: MaskLanguageModelDataset
  dataset_config: *train_dataset
