base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/bloom_dataset.yaml',
    './model_config/bloom_560m.yaml',
    '../__base__.yaml' ]

context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  device_id: 0

parallel:
  parallel_optimizer_config: {"gradient_accumulation_shard": False}
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False
  loss_repeated_mean: True
  full_batch: True # if False, export PIPELINE_SLICE_SKIP_REDISTRIBUTION=1, else True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True  # optimizer shard
  # strategy_ckpt_save_file: "./ckpt_strategy.ckpt"

recompute_config:
  recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

parallel_config:
  data_parallel: 2
  model_parallel: 4
  pipeline_stage: 8
  optimizer_shard: True
  micro_batch_num: 16
  vocab_emb_dp: True
  gradient_aggregation_group: 4

# runner config
runner_config:
  epochs: 1
  batch_size: 1
  sink_mode: True
  per_epoch_size: 1
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4294967296
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 0.00000001 # 1e-8
  weight_decay: 0.1

# lr sechdule
lr_schedule:
  type: polynomial
  learning_rate: 0.0001
  lr_end: 0.00001
  warmup_steps: 0
  total_steps: -1 # -1 means it will load the total steps of the dataset

callbacks:
  - type: MFLossMonitor
  - type: SummaryMonitor
    keep_default_action: True
  - type: CheckpointMointor
    prefix: "mindformers"
    save_checkpoint_steps: 1000
    integrated_save: False
    async_save: False
  - type: ObsMonitor

auto_tune: True
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 74

use_parallel: True

micro_batch_interleave_num: 1

seed: 0
resume_or_finetune_checkpoint: ""


run_mode: 'train'
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'bloom'

