model:
  model_config:
    type: BloomConfig
    seq_length: 20
    vocab_size: 250880
    embedding_size: 64
    num_layers: 2
    num_heads: 8
    expand_ratio: 4
    hidden_act: "gelu"
    dropout_prob: 0.0
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    initializer_range: 0.02
    param_init_type: "float32"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    compute_dtype: "float16"
    checkpoint_name_or_path: "bloom"
    eos_token: 0
    repetition_penalty: 1
    max_decode_length: 1024
    top_k: 5
    top_p: 1
    do_sample: True
  arch:
    type: BloomLMHeadModel

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<|endoftext|>'
    bos_token: '<|endoftext|>'
    eos_token: '<|endoftext|>'
    pad_token: '<|endoftext|>'
    type: GPT2Tokenizer
  type: GPT2Processor
