model:
  model_config:
    type: BloomConfig
    seq_length: 2048
    vocab_size: 94208
    embedding_size: 8192
    num_layers: 32    # 80
    num_heads: 64
    expand_ratio: 4
    hidden_act: "fast_gelu"
    dropout_prob: 0.0
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    initializer_range: 0.02
    param_init_type: "float16"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    compute_dtype: "float16"
    checkpoint_name_or_path: "bloom"
    eos_token: 2
    repetition_penalty: 1
    max_decode_length: 1024
    top_k: 5
    top_p: 1
    do_sample: True
  arch:
    type: BloomLMHeadModel